# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Game.create!([
  { :name => "Pandemic", :created_at => "2013-11-10 00:50:14", :updated_at => "2013-11-10 00:50:14" },
  { :name => "Ticket to Ride", :created_at => "2013-11-11 02:35:46", :updated_at => "2013-11-11 02:35:46" }
])



Participation.create!([
  { :session_id => 1, :player_id => 1, :role_id => 1, :score => nil, :created_at => "2013-11-10 00:51:39", :updated_at => "2013-11-10 00:51:39" },
  { :session_id => 1, :player_id => 2, :role_id => 2, :score => nil, :created_at => "2013-11-10 00:51:49", :updated_at => "2013-11-10 00:51:49" },
  { :session_id => 2, :player_id => 3, :role_id => 3, :score => nil, :created_at => "2013-11-10 00:52:34", :updated_at => "2013-11-10 00:52:34" },
  { :session_id => 2, :player_id => 4, :role_id => 4, :score => nil, :created_at => "2013-11-10 00:52:45", :updated_at => "2013-11-10 00:52:45" },
  { :session_id => 3, :player_id => 1, :role_id => 2, :score => nil, :created_at => "2013-11-10 01:13:53", :updated_at => "2013-11-10 01:13:53" },
  { :session_id => 3, :player_id => 3, :role_id => 4, :score => nil, :created_at => "2013-11-10 01:14:07", :updated_at => "2013-11-10 01:14:07" }
])



Player.create!([
  { :name => "Alissa", :email => "", :created_at => "2013-11-10 00:50:27", :updated_at => "2013-11-10 00:50:27" },
  { :name => "Diana", :email => "", :created_at => "2013-11-10 00:50:32", :updated_at => "2013-11-10 00:50:32" },
  { :name => "Felix", :email => "", :created_at => "2013-11-10 00:50:38", :updated_at => "2013-11-10 00:50:38" },
  { :name => "Sean", :email => "", :created_at => "2013-11-10 00:50:43", :updated_at => "2013-11-10 00:50:43" }
])



Role.create!([
  { :name => "Medic", :game_id => 1, :created_at => "2013-11-10 00:50:54", :updated_at => "2013-11-10 07:22:47" },
  { :name => "Field Operative", :game_id => 1, :created_at => "2013-11-10 00:51:01", :updated_at => "2013-11-10 00:51:01" },
  { :name => "Field Director", :game_id => 1, :created_at => "2013-11-10 00:51:08", :updated_at => "2013-11-10 00:51:08" },
  { :name => "Researcher", :game_id => 1, :created_at => "2013-11-10 00:51:15", :updated_at => "2013-11-10 00:51:15" },
  { :name => "Scientist", :game_id => 1, :created_at => "2013-11-10 03:58:24", :updated_at => "2013-11-10 03:58:24" },
  { :name => "Virologist", :game_id => 1, :created_at => "2013-11-10 04:33:50", :updated_at => "2013-11-10 04:33:50" },
  { :name => "Conductor", :game_id => 2, :created_at => "2013-11-11 02:35:46", :updated_at => "2013-11-11 02:35:46" }
])



Session.create!([
  { :game_id => 2, :date => "2013-11-10 00:51:00", :comments => "Close but we won", :created_at => "2013-11-10 00:51:27", :updated_at => "2013-11-11 02:36:13", :is_stalemate => false },
  { :game_id => 1, :date => "2013-11-09 00:51:00", :comments => "Epic failure", :created_at => "2013-11-10 00:51:59", :updated_at => "2013-11-10 02:41:12", :is_stalemate => true },
  { :game_id => 1, :date => "2013-11-07 01:13:00", :comments => "Lost again", :created_at => "2013-11-10 01:13:36", :updated_at => "2013-11-10 02:42:24", :is_stalemate => true },
  { :game_id => 1, :date => "2013-11-04 05:13:00", :comments => "Did anyone play this game? ", :created_at => "2013-11-10 05:14:11", :updated_at => "2013-11-10 05:14:11", :is_stalemate => false },
  { :game_id => 1, :date => "2013-11-04 00:46:00", :comments => "Umm, more ghost games.", :created_at => "2013-11-11 00:46:51", :updated_at => "2013-11-11 00:46:51", :is_stalemate => false }
])


